# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/PyCQA/isort
  rev: 5.6.4
  hooks:
    - id: isort
- repo: https://github.com/myint/autoflake
  rev: v1.4
  hooks:
    - id: autoflake
      args: [--in-place, --remove-unused-variables, --remove-all-unused-imports, --remove-duplicate-keys]
- repo: https://github.com/python/black
  rev: 20.8b1
  hooks:
    - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.790
  hooks:
    - id: mypy
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
    - id: flake8
      additional_dependencies:
        - flake8-bugbear
- repo: https://github.com/Lowess/pre-commit-hooks
  rev: v1.3.0
  hooks:
    - id: jinja2-render-template
      files: btn/templates/metadata_1.0.0.sql
      args: [btn/templates/metadata_1.0.0.sql, --output, btn/sql/metadata_1.0.0.sql]
      always_run: false
